### PR TITLE
Configure travis to run all the tests

### LINKED ISSUE #15: Add CI for testing
Could be done in similar manner as in React integration - https://github.com/ckeditor/ckeditor4-react/blob/master/.travis.yml.

### PR DESCRIPTION
**Pull request by engineering-this**
Fully enabled CI Travis testing.

- Chrome & Firefox are run directly by the Travis.
- Edge & Safari are run in BrowserStack.

E2E tests are run only for Chrome, because they use Selenium/WebDriver to control browser.

Closes #15

### CODE REVIEW

**Comment by f1ames** [comment]
Rebased on the latest `master`.

**Comment by f1ames** [comment]
Also added badges to README file.

**Comment by engineering-this** [comment]
I've added one dependency `karma-spec-reporter` and used it instead of `progress` reporter. Additionally I've turned off capturing browser logs by karma. Errors will be still captured by reporter itself.
Only issue remaining is that test are run asynchronously and successful messages are printed right after test, so they are not correctly ordered, browsers are mixed, etc. To make it less noisy I added an option to not log ✅ tests for travis, but they are still visible when run locally.

Only visible tests comes from protractor e2e tests, but there are just 6 tests for one browser, so I think it can stay this way.

**Comment by f1ames** [comment]
Rebased on the latest `master`.

**Pull request merged**
