### PR TITLE
Enable ivy for angular 16

### LINKED ISSUE #242: Ivy compiler for Angular v13 and later
Hi !

Has expected with angular 16 :

> Error: src/app/app.module.ts:207:5 - error NG6002: 'CKEditorModule' does not appear to be an NgModule class.
> 
> 207     CKEditorModule,
>         ~~~~~~~~~~~~~~
> 
>   node_modules/ckeditor4-angular/ckeditor.module.d.ts:5:22
>     5 export declare class CKEditorModule {
>                            ~~~~~~~~~~~~~~
>     This likely means that the library (ckeditor4-angular) which declares CKEditorModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
> 
Any solution ?  workaround?

cheers

### PR DESCRIPTION
**Pull request by Mooeeezzzz**
https://angular.io/guide/update-to-version-16#angular-compatibility-compiler-ngcc-has-been-removed
updates angular and ng-packagr to v13 which by default support partial compilation https://angular.io/guide/angular-compiler-options#compilationmode

closes  #242

### CODE REVIEW

**Comment by Comandeer** [comment]
@Mooeeezzzz, thx for the contribution! Could you elaborate on what changes you introduced and why they were needed?

**Comment by Mooeeezzzz** [comment]
@Comandeer can we merge this since without it you can't use this package with angular newest 16 version ?

**Review by ezintz — APPROVED** [review]
The changes are looking good to me. Probably this is a new major, since the Angular version has been upgraded. I guess a lot of guys would like to continue using CKEditor4 with Angular, so maybe we can get it merged. 🎉

This will solve #242 which has been closed, because we did not react. Let's keep everyone happy, if possible 😅

**Comment by Muntazir86** [comment]
@Mooeeezzzz  thanks for your contribution. can you let me you when this pull request will be merged.

**Review by Comandeer — APPROVED** [review]
LGTM! I've just updated the required Angular versions in the `src/ckeditor/package.json` file.

**Comment by Nickolaus** [comment]
any plans for a tagged release here?

**Pull request merged**
