### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Comandeer**
I've updated deps to the maximum possible version. Unfortunately, we're stuck with Angular 12.x for a while as newer one does not officially support IE11.

### CODE REVIEW

**Comment by Comandeer** [comment]
It seems that Safari fails constantly on one of the timeouts :thinking:. I'll check if downgrading jasmine resolves the issue.

**Comment by Comandeer** [comment]
Not sure why builds error due to error in Travis config as config seems to be valid… Checked in the [official validator](https://config.travis-ci.com/explore).

**Comment by Comandeer** [comment]
Ok, CI started working again and now tests are passing 🎉

**Review by MMMalik — APPROVED** [review]
LGTM!

**Pull request merged**
